import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..')
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'))
const required=[
  'apps/hub/src/worker.mjs','apps/hub/src/lib.mjs','apps/hub/public/index.html','apps/hub/public/app.js','apps/hub/public/skin-preview-3d.js','apps/hub/public/styles.css',
  'apps/orchestrator/server.mjs','apps/orchestrator/world-config.mjs','apps/orchestrator/world-version.mjs','apps/orchestrator/Dockerfile','apps/proxy/server.cjs','apps/proxy/Dockerfile',
  'apps/server-plugin/build.gradle.kts','apps/server-plugin/src/main/java/com/hemcraft/gate/HEMGatePlugin.java',
  'apps/client/build-client.mjs','apps/client/hem-bridge.js','tests/system/required-gates-1215.json','tests/system/launcher-3d.mjs','tests/system/static-hub.mjs','tests/system/backup-restore-drill.sh','scripts/verify-certification.mjs','scripts/reconcile-release-blockers.mjs','scripts/verify-production-r2-evidence.mjs','scripts/verify-manual-acceptance.mjs','scripts/doctor.mjs','scripts/source-manifest.mjs','infra/production-r2-drill.sh','infra/docker-compose.yml','infra/Caddyfile','infra/preflight.sh','scripts/preflight.mjs','scripts/render-cloudflare-config.mjs','.github/workflows/deploy-cloudflare.yml','README.md','docs/ACCEPTANCE.md','docs/MANUAL_ACCEPTANCE.md','docs/RELEASE_BLOCKERS.md'
]
for(const f of required)if(!fs.existsSync(path.join(root,f)))throw new Error(`Missing required release file: ${f}`)
for(const f of [
  'apps/hub/src/worker.mjs','apps/hub/src/lib.mjs','apps/hub/public/app.js','apps/hub/public/skin-preview-3d.js','apps/orchestrator/server.mjs','apps/orchestrator/world-config.mjs','apps/orchestrator/world-version.mjs','apps/client/build-client.mjs','apps/client/hem-bridge.js','scripts/verify-certification.mjs','scripts/reconcile-release-blockers.mjs','scripts/verify-production-r2-evidence.mjs','scripts/verify-manual-acceptance.mjs','scripts/doctor.mjs'
]) execFileSync(process.execPath,['--check',path.join(root,f)],{stdio:'inherit'})
const files=[]; const walk=d=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){if(['node_modules','.git','upstream','dist','artifacts'].includes(e.name))continue;const p=path.join(d,e.name);e.isDirectory()?walk(p):files.push(p)}};walk(root)
for(const p of files){const rel=path.relative(root,p);const st=fs.statSync(p);if(st.size>5*1024*1024)throw new Error(`Unexpected large source artifact: ${rel}`)}
const hub=fs.readFileSync(path.join(root,'apps/hub/src/worker.mjs'),'utf8')
const orch=fs.readFileSync(path.join(root,'apps/orchestrator/server.mjs'),'utf8')
const worldConfig=fs.readFileSync(path.join(root,'apps/orchestrator/world-config.mjs'),'utf8')
const worldVersion=fs.readFileSync(path.join(root,'apps/orchestrator/world-version.mjs'),'utf8')
const client=fs.readFileSync(path.join(root,'apps/client/build-client.mjs'),'utf8')
const plugin=fs.readFileSync(path.join(root,'apps/server-plugin/src/main/java/com/hemcraft/gate/HEMGatePlugin.java'),'utf8')
const bridge=fs.readFileSync(path.join(root,'apps/client/hem-bridge.js'),'utf8')
const hubApp=fs.readFileSync(path.join(root,'apps/hub/public/app.js'),'utf8')
const skinPreview=fs.readFileSync(path.join(root,'apps/hub/public/skin-preview-3d.js'),'utf8')
const gateSpec=JSON.parse(fs.readFileSync(path.join(root,'tests/system/required-gates-1215.json'),'utf8'))
const certVerifier=fs.readFileSync(path.join(root,'scripts/verify-certification.mjs'),'utf8')
const launcherAcceptance=fs.readFileSync(path.join(root,'tests/system/launcher-3d.mjs'),'utf8')
const restoreDrill=fs.readFileSync(path.join(root,'tests/system/backup-restore-drill.sh'),'utf8')
const deploy=fs.readFileSync(path.join(root,'.github/workflows/deploy-cloudflare.yml'),'utf8')
const system=fs.readFileSync(path.join(root,'tests/system/browser-1215.mjs'),'utf8')
const hardcoreMigration=fs.readFileSync(path.join(root,'apps/hub/migrations/0005_world_hardcore.sql'),'utf8')
const restore=fs.readFileSync(path.join(root,'infra/restore-r2.sh'),'utf8')
const backup=fs.readFileSync(path.join(root,'infra/backup-r2.sh'),'utf8')
const productionR2Drill=fs.readFileSync(path.join(root,'infra/production-r2-drill.sh'),'utf8')
const productionR2Verifier=fs.readFileSync(path.join(root,'scripts/verify-production-r2-evidence.mjs'),'utf8')
const manualVerifier=fs.readFileSync(path.join(root,'scripts/verify-manual-acceptance.mjs'),'utf8')
const releaseReadiness=fs.readFileSync(path.join(root,'scripts/release-readiness.mjs'),'utf8')
const sourceManifestTool=fs.readFileSync(path.join(root,'scripts/source-manifest.mjs'),'utf8')
const doctor=fs.readFileSync(path.join(root,'scripts/doctor.mjs'),'utf8')
const packageTool=fs.readFileSync(path.join(root,'scripts/package.mjs'),'utf8')
const parityLedger=fs.readFileSync(path.join(root,'docs/PARITY_1_21_5.md'),'utf8')
const workflow1215=fs.readFileSync(path.join(root,'.github/workflows/system-1215.yml'),'utf8')
const systemCompose=fs.readFileSync(path.join(root,'tests/system/docker-compose.yml'),'utf8')
const checks=[
  ['orchestrator image includes imported runtime modules',/COPY apps\/orchestrator\/world-config\.mjs \.\/world-config\.mjs/.test(fs.readFileSync(path.join(root,'apps/orchestrator/Dockerfile'),'utf8'))&&/COPY apps\/orchestrator\/world-version\.mjs \.\/world-version\.mjs/.test(fs.readFileSync(path.join(root,'apps/orchestrator/Dockerfile'),'utf8'))],
  ['Paper 1.21.5 build 114 authority',/1\.21\.5/.test(orch)&&/PAPER_BUILD[^\n]+114/.test(orch)&&/2ae6ae22adf417699746e0f89fc2ef6cb6ee050a5f6608cee58f0535d60b509e/.test(orch)],['one world per Paper dir',/path\.join\(ROOT,id\)/.test(orch)],
  ['launch token one-use',/consumed_at IS NULL/.test(hub)&&/UPDATE launch_sessions SET consumed_at/.test(hub)],
  ['membership gate',/requireMembership/.test(hub)],['client 1.21.5 target',/supportedVersions\.mjs/.test(client)&&/1\.21\.5/.test(client)&&/minecraftRenderer: dependencyVersion\('minecraft-renderer'/.test(client)&&/minecraftInventory: dependencyVersion\('minecraft-inventory'/.test(client)&&/mineflayerConnector: dependencyVersion\('mcraft-fun-mineflayer'/.test(client)&&/--frozen-lockfile/.test(client)],
  ['auto connect explicit',/allowAutoConnect\s*=\s*true/.test(client)],['Paper auth gate',/HEM launch authorization expired/.test(plugin)],
  ['secrets not query params',!/searchParams\.set\(['"]hemToken/.test(fs.readFileSync(path.join(root,'apps/hub/src/lib.mjs'),'utf8'))],
  ['graceful Paper shutdown',/save-all flush/.test(orch)&&/45_000/.test(orch)],
  ['timestamped player presence',/presenceClock/.test(orch)&&/at>=previous\.at/.test(orch)],
  ['production deployment preflight',/preflight:production/.test(deploy)],
  ['custom skin Paper profile propagation',/ProfileProperty\(\"textures\"/.test(plugin)&&/setPlayerProfile\(profile\)/.test(plugin)&&/i\.skin_model,i\.skin_png,i\.profile_updated_at/.test(hub)],
  ['skin endpoint WebGL CORS',/access-control-allow-origin/.test(hub)&&/cross-origin-resource-policy/.test(hub)],
  ['1.21.5 registry integrity before bundle',/minecraft-data'\)\('1\.21\.5'\)/.test(client)&&/firefly_bush/.test(client)&&/cactus_flower/.test(client)&&/roundTrip\(mcData\.itemsArray/.test(client)&&/roundTrip\(mcData\.blocksArray/.test(client)&&/roundTrip\(mcData\.entitiesArray/.test(client)&&/version !== 770/.test(client)],
  ['1.21.5 modern item-definition assets before bundle',/mc-assets\/package\.json/.test(client)&&/itemDefinitions\.json/.test(client)&&/hasOwnProperty\.call\(itemDefinitions, '1\.21\.5'\)/.test(client)&&/firefly_bush/.test(client)&&/mcAssets: assetsPackage\.version/.test(client)],
  ['upstream browser capability contract',/capabilityPatterns/.test(client)&&/keybindings/.test(client)&&/renderDistanceSetting/.test(client)&&/rawMouseInput/.test(client)&&/resourcePackTextures/.test(client)&&/creativeInventory/.test(client)&&/thirdPerson/.test(client)&&/sounds/.test(client)&&/capabilities,/.test(client)],
  ['upstream release + protocol attestation',/upstreamReleaseTag/.test(client)&&/upstreamLiteralVersionTokens/.test(client)&&/upstreamSupportedVersionsSha256/.test(client)&&/upstreamPackageSha256/.test(client)&&/upstreamLockSha256/.test(client)&&/frozenLockfile: true/.test(client)&&/protocolVerified1215/.test(client)&&/compatibilityMode/.test(system)&&/upstreamReleaseTag/.test(certVerifier)],
  ['visible client compatibility failure UX',/hem-compatibility-error/.test(bridge)&&/build-identity/.test(bridge)&&/registry-1215/.test(bridge)&&/renderer-1215/.test(bridge)&&/authorization/.test(bridge)],
  ['orchestrator runtime/startup integrity guard',/runtimeConfigErrors/.test(orch)&&/configFingerprint/.test(orch)&&/Paper exited before ready/.test(orch)&&/HEMGate plugin jar is missing or unreadable/.test(orch)],
  ['1.21.5 world downgrade safety guard',/assertWorldCompatible/.test(orch)&&/HEM_TARGET_DATA_VERSION = 4325/.test(worldVersion)&&/DataVersion/.test(worldVersion)&&/refusing unsafe downgrade/.test(worldVersion)],
  ['live acceptance doctor',/hem-doctor\.json/.test(doctor)&&/network\.paper-1215/.test(doctor)&&/client\.identity/.test(doctor)&&/npm run doctor:system/.test(workflow1215)],
  ['HEM client launch settings',/withClientSettings/.test(hubApp)&&/renderDistance/.test(hubApp)&&/modal', 'keybindings/.test(hubApp)],
  ['runtime parity diagnostics',/__HEM_PARITY__/.test(bridge)&&/registry\.ok/.test(bridge)&&/windowsOpened/.test(bridge)&&/sectionObjects/.test(bridge)&&/renderer\.healthy/.test(bridge)],
  ['launcher interactive WebGL Classic/Slim skin preview',/renderSkinPreview3D/.test(hubApp)&&/normalizeLegacySkin/.test(hubApp)&&/Legacy 64×32 skin normalized/.test(hubApp)&&/getContext\('webgl'/.test(skinPreview)&&/model === 'slim'/.test(skinPreview)&&/pointermove/.test(skinPreview)&&/faceMap\(48,48,armW,12,4\)/.test(skinPreview)],
  ['launcher 3D preview has executable browser acceptance',/hem-launcher-certification\.json/.test(launcherAcceptance)&&/dataset\.preview === 'webgl-3d'/.test(launcherAcceptance)&&/setInputFiles\('#regSkin'/.test(launcherAcceptance)&&/dragRotate/.test(launcherAcceptance)&&/legacyNormalized/.test(launcherAcceptance)&&/settingsPersisted/.test(launcherAcceptance)&&/legacy\.png/.test(launcherAcceptance)&&/Verify interactive Classic\/Slim 3D launcher skin preview/.test(fs.readFileSync(path.join(root,'.github/workflows/system-1215.yml'),'utf8'))],
  ['deployed client identity verification',/Verify deployed HEM client identity/.test(deploy)&&/hem-build\.json/.test(deploy)&&deploy.includes(pkg.version)],
  ['world-level Allow Commands reaches Paper',/allow_commands/.test(hub)&&/enable-command-block/.test(worldConfig)&&/allow-commands/.test(orch)&&/setOp\(lease\.commandsAuthorized\(\)\)/.test(plugin)&&/toggle-commands/.test(hubApp)],
  ['native world creation options',/world_type/.test(hub)&&/generate_structures/.test(hub)&&/hardcore/.test(hub)&&/hardcore/.test(worldConfig)&&/level-type/.test(worldConfig)&&/cycle-world-type/.test(hubApp)&&/toggle-structures/.test(hubApp)],
  ['Hardcore D1 persistence is backward-safe',/ADD COLUMN hardcore/.test(hardcoreMigration)&&/storedGameMode = hardcore \? 'survival'/.test(hub)&&/world\.hardcore === 1 \? 'hardcore'/.test(hub)],
  ['owner-only world edit/rename flow',/async function renameWorld/.test(hub)&&/Only the world owner can rename/.test(hub)&&/edit-selected/.test(hubApp)&&/saveWorldEdit/.test(hubApp)],
  ['renderer health gate',/rendered chunk sections/.test(system)&&/modern block registry states with live rendered chunk sections/.test(system)],
  ['survival-loop system gate expanded',/client-originated block placement synchronization/.test(system)&&/both browsers remain connected and render healthy chunk sections after client placement/.test(system)&&/forward\+jump traverses a one-block obstacle/.test(system)&&/browser crafting recipe execution/.test(system)&&/3x3 crafting-table recipe/.test(system)&&/furnace fuel\/input\/progress\/output synchronization/.test(system)&&/dropped-item entity synchronization/.test(system)&&/piston\/redstone movement synchronization/.test(system)&&/hopper transfer\/container state synchronization/.test(system)&&/remote armor\/offhand equipment synchronization/.test(system)&&/barrel contents in browser container/.test(system)&&/shulker-box contents in browser container/.test(system)&&/smoker \+ blast-furnace recipe processing/.test(system)&&/browser player mounts and dismounts a native minecart/.test(system)&&/Ender chest leaked Hudson contents to Elise/.test(system)&&/repeater powered state/.test(system)&&/server-authoritative fall damage/.test(system)&&/server-authoritative night time reaches browser/.test(system)&&/representative entity family/.test(system)&&/redstone dust analog-power propagation/.test(system)&&/client-origin respawn/.test(system)&&/worldborder set 8/.test(system)],
  ['rotating one-use browser refresh lease',/RESUME_TTL_MS/.test(plugin)&&/resumeSessions\.remove\(token\)/.test(plugin)&&/sendPluginMessage\(this, SESSION_CHANNEL/.test(plugin)&&/sessionStorage\.setItem\(resumeKey/.test(bridge)&&/\/hem resume/.test(bridge)],
  ['live custom-skin reannouncement gate',/hidePlayer\(this, player\)/.test(plugin)&&/showPlayer\(this, player\)/.test(plugin)&&/Elise renderer fetches Hudson custom skin/.test(system)&&/Hudson renderer fetches Elise custom skin/.test(system)],
  ['forced Paper crash recovery gate',/HEM_ENABLE_TEST_FAULTS/.test(orch)&&/\/internal\/test\/kill-world/.test(orch)&&/forced active-Paper crash recovery/.test(system)&&/HEM_ENABLE_TEST_FAULTS:\s*[\"']?true/.test(systemCompose)],
  ['R2 verified backup + restore safety contract',/cd "\$TMP".*sha256sum hem-worlds\.tar\.gz/s.test(backup)&&/docker compose ps -aq orchestrator/.test(backup)&&/rclone check/.test(backup)&&/trap 'exit 130' INT/.test(backup)&&/RESTORE_CONFIRM/.test(restore)&&/sha256sum -c hem-worlds\.tar\.gz\.sha256/.test(restore)&&restore.includes(`HEM: ${pkg.version}`)&&/Paper: 1\.21\.5 build 114/.test(restore)&&/docker compose ps -aq orchestrator/.test(restore)&&/trap 'exit 130' INT/.test(restore)&&/pre-restore-worlds/.test(restore)&&/level\.dat/.test(restore)],
  ['transient proxy outage recovery gate',/compose\('stop', '-t', '15', 'proxy'\)/.test(system)&&/Hudson observes proxy outage/.test(system)&&/Elise observes proxy outage/.test(system)&&/compose\('start', 'proxy'\)/.test(system)&&/transient proxy outage \+ same-tab resume recovery/.test(system)],
  ['60-minute certification soak contract',(()=>{const m=/timeout-minutes:\s*(\d+)/.exec(workflow1215);return /HEM_SOAK_MINUTES/.test(system)&&/60_000/.test(system)&&/two-browser stability soak/.test(system)&&!!m&&Number(m[1])>=120})()],
  ['final upstream commit pin contract',/HEM_REQUIRE_PINNED_MWC/.test(client)&&/exact 40-character upstream commit SHA/.test(client)&&/upstreamPinned:/.test(client)&&/default: 0359f20b8d721ea44c7ddb633c985a71574c73d3/.test(fs.readFileSync(path.join(root,'.github/workflows/system-1215.yml'),'utf8'))&&/HEM_REQUIRE_PINNED_MWC: 'true'/.test(fs.readFileSync(path.join(root,'.github/workflows/system-1215.yml'),'utf8'))&&/HEM_REQUIRE_PINNED_CERT: 'true'/.test(fs.readFileSync(path.join(root,'.github/workflows/system-1215.yml'),'utf8'))&&/HEM_REQUIRE_PINNED_MWC: 'true'/.test(deploy)&&/d\.upstreamPinned!==true/.test(deploy)&&/--frozen-lockfile/.test(client)&&!/--no-frozen-lockfile/.test(client)&&/upstreamLockSha256/.test(client)&&/frozenLockfile: true/.test(client)],
  ['machine-readable system certification artifact',/hem-1215-certification\.json/.test(system)&&/acceptance: 'passed'/.test(system)&&/upstreamCommit: buildIdentity\.upstreamCommit/.test(system)&&/soakMinutes: SOAK_MINUTES/.test(system)&&/gates: \[\.\.\.passedGates\]\.sort/.test(system)&&gateSpec.required.includes('inventory.armor-offhand')&&gateSpec.required.includes('movement.vehicle-mount')&&gateSpec.required.includes('containers.shulker-box')&&gateSpec.required.includes('containers.special-furnaces')&&gateSpec.required.includes('movement.obstacle-jump')&&gateSpec.required.includes('render.post-placement-stability')&&gateSpec.required.includes('world.time-weather')&&gateSpec.required.includes('blocks.state-families')&&gateSpec.required.includes('entities.projectile-sentinels')&&gateSpec.required.includes('progression.experience')],
  ['certification evidence is independently verified',/HEM_REQUIRE_PINNED_CERT/.test(certVerifier)&&/Certification missing required gates/.test(certVerifier)&&/expectedVersion/.test(certVerifier)&&/package\.json/.test(certVerifier)&&/npm run verify:certification/.test(fs.readFileSync(path.join(root,'.github/workflows/system-1215.yml'),'utf8'))],
  ['backup restore rollback has executable system acceptance',/HEM_RESTART_SERVICES/.test(backup)&&/HEM_RESTART_SERVICES/.test(restore)&&/hem-restore-certification\.json/.test(restoreDrill)&&/automaticRollback/.test(restoreDrill)&&/invalidArchiveRejectedAfterMutation/.test(restoreDrill)&&/rclone-local-filesystem/.test(restoreDrill)&&/Backup\/restore certification is incomplete/.test(certVerifier)&&/Install deterministic restore-drill transport/.test(fs.readFileSync(path.join(root,'.github/workflows/system-1215.yml'),'utf8'))&&/tests\/system\/backup-restore-drill\.sh/.test(fs.readFileSync(path.join(root,'.github/workflows/system-1215.yml'),'utf8'))],
  ['finite production release gate',fs.existsSync(path.join(root,'docs/RELEASE_BLOCKERS.md'))&&fs.existsSync(path.join(root,'scripts/release-readiness.mjs'))&&/release-readiness\.mjs/.test(fs.readFileSync(path.join(root,'scripts/release-guard.mjs'),'utf8'))&&!/parity-report\.mjs'\), \['--final'\]/.test(fs.readFileSync(path.join(root,'scripts/release-guard.mjs'),'utf8'))],
  ['evidence-derived final release blockers',/verify-certification\.mjs/.test(releaseReadiness)&&/verify-production-r2-evidence\.mjs/.test(releaseReadiness)&&/verify-manual-acceptance\.mjs/.test(releaseReadiness)&&/cloudflare-r2/.test(productionR2Verifier)&&/HEM_DISPOSABLE_R2_DRILL/.test(productionR2Drill)&&/emptyVolumeRestore/.test(productionR2Drill)&&/automaticRollback/.test(productionR2Drill)&&/unchecked required item/.test(manualVerifier)],
  ['reproducible source manifest before packaging',/SOURCE_MANIFEST\.sha256/.test(sourceManifestTool)&&/sha256/.test(sourceManifestTool)&&/--write/.test(sourceManifestTool)&&/source-manifest\.mjs/.test(packageTool)],
  ['zero-TODO implementation coverage with strict full-parity guard',!/^- TODO /m.test(parityLedger)&&pkg.scripts['parity:full']==='node scripts/parity-report.mjs --final'&&gateSpec.required.length>=120&&gateSpec.required.every(g=>system.includes(`pass('${g}'`)||system.includes(`pass(\"${g}\"`))],
  ['native 1.21.5 gameplay mechanics beyond registry sentinels',gateSpec.required.length>=120&&['commands.command-block-edit','redstone.crafter-recipe','world.fluid-buckets','redstone.dispenser-fluid','blocks.copper-actions','entities.golem-creation','entities.breeding','bosses.wither-structure-spawn','survival.food-consumption','movement.boat-control','blocks.cauldron-composter-actions','items.enchanting','items.anvil-rename','entities.ender-pearl-use','movement.swimming','movement.ladder-climb','movement.scaffolding-climb','redstone.sticky-slime','redstone.daylight-sensor','dimensions.portal-ignition','survival.fishing','dimensions.bed-spawn'].every(g=>gateSpec.required.includes(g)&&system.includes(`pass('${g}'`))&&/process\.env\.MWC_REF \|\| '0359f20b8d721ea44c7ddb633c985a71574c73d3'/.test(client)&&/for \(const name of spawnEggs\)/.test(client)],
  ['RC13 parity closure mechanics',gateSpec.required.length>=135&&['world.seed-authority','blocks.wall-state','movement.vine-climb','movement.bubble-column','blocks.bookshelf-pot-actions','redstone.observer-action','entities.taming','combat.shield-block','dimensions.respawn-anchor-spawn','containers.mount-inventory-semantics'].every(g=>gateSpec.required.includes(g)&&system.includes(`pass('${g}'`))&&/Paper reports the configured shared-world seed/.test(system)&&/browser-fed wolf acquires owner UUID/.test(system)&&/client respawns near valid Nether respawn anchor/.test(system)],
  ['RC13 second parity closure mechanics',gateSpec.required.length>=142&&['items.brewing-recipe','items.smithing-recipe','items.grindstone-action','redstone.tripwire-action','commands.command-minecart','survival.death-drops','dimensions.end-gateway'].every(g=>gateSpec.required.includes(g)&&system.includes(`pass('${g}'`))&&/browser brewing produces awkward potion component/.test(system)&&/command-block minecart executes on powered activator rail/.test(system)&&/native End Gateway teleports browser player to exact exit/.test(system)],
  ['RC13 third parity closure mechanics',gateSpec.required.length>=146&&['progression.enchant-cost','items.anvil-cost','world.border-damage','movement.powder-snow'].every(g=>gateSpec.required.includes(g)&&system.includes(`pass('${g}'`))&&/enchanting consumes browser XP levels/.test(system)&&/world-border damage reaches browser health state/.test(system)&&/powder-snow sink\/support semantics differ with leather boots/.test(system)],
  ['RC13 fourth parity closure mechanics',gateSpec.required.length>=152&&['items.bundle-storage','items.anvil-repair','containers.furnace-xp','blocks.archaeology-brushing','combat.attack-cooldown','combat.critical-hit'].every(g=>gateSpec.required.includes(g)&&system.includes(`pass('${g}'`))&&/native bundle component/.test(system)&&/anvil combines damaged swords/.test(system)&&/furnace result awards browser XP/.test(system)&&/suspicious-sand archaeology cycle/.test(system)&&/attack cooldown scaling failed/.test(system)&&/critical hit scaling failed/.test(system)],
  ['RC13 fifth parity closure mechanics',gateSpec.required.length>=157 && ['redstone.target-action','redstone.activator-rail-action','redstone.torch-burnout','containers.beacon-effect','bosses.dragon-fight-state'].every(g => gateSpec.required.includes(g) && system.includes(`pass('${g}'`)) && /target-block analog redstone output/.test(system) && /powered activator rail ejects browser rider/.test(system) && /redstone torch enters burnout/.test(system) && /set_beacon_effect/.test(system) && /native dragon death generates End exit portal/.test(system)],
  ['RC13 sixth parity closure mechanics',gateSpec.required.length>=163&&['combat.shield-angle','combat.protection-enchant','combat.fire-aspect','survival.totem','items.potion-milk','world.border-updates'].every(g=>gateSpec.required.includes(g)&&system.includes(`pass('${g}'`))&&/rear projectile bypasses frontal shield arc/.test(system)&&/Protection enchantment mitigation failed/.test(system)&&/browser Fire Aspect hit ignites target/.test(system)&&/totem prevents lethal damage and is consumed/.test(system)&&/browser drinking milk clears active potion effects/.test(system)&&/world_border_lerp_size/.test(system)],
]
for(const [name,ok] of checks){if(!ok)throw new Error(`Release contract failed: ${name}`);console.log(`PASS ${name}`)}
console.log(`Verified ${files.length} source files; ${checks.length} release contracts.`)
